# Generated by Django 3.0.5 on 2023-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='content',
            field=models.TextField(max_length=200, verbose_name='コンテンツ'),
        ),
    ]
